### ISSUE TITLE
BLE compile error

### ISSUE THREAD

**Issue by kosmostrater** [cifertech/nRFBox#63]
When Trying to compile I get this error. Tried to compile several PC's
using Arduino 1.8.19 ISE
Tried ESP32 Dev,  ESP32 Wroom, ESP32-S3. Always get the same error

C:\Users\user\Documents\Arduino\nRFBox\nRFBox_V2\blescan.cpp: In function 'void blescanLoop()':
blescan.cpp:71:32: error: no match for 'operator=' (operand types are 'BLEScanResults' and 'BLEScanResults*')
   71 |     results = scan->getResults();
      |                                ^
In file included from C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertisedDevice.h:20,
                 from C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEClient.h:25,
                 from C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEDevice.h:22,
                 from C:\Users\user\Documents\Arduino\nRFBox\nRFBox_V2\blescan.h:9,
                 from C:\Users\user\Documents\Arduino\nRFBox\nRFBox_V2\blescan.cpp:7:
C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEScan.h:48:7: note: candidate: 'BLEScanResults& BLEScanResults::operator=(const BLEScanResults&)'
   48 | class BLEScanResults {
      |       ^~~~~~~~~~~~~~
C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEScan.h:48:7: note:   no known conversion for argument 1 from 'BLEScanResults*' to 'const BLEScanResults&'
C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEScan.h:48:7: note: candidate: 'BLEScanResults& BLEScanResults::operator=(BLEScanResults&&)'
C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEScan.h:48:7: note:   no known conversion for argument 1 from 'BLEScanResults*' to 'BLEScanResults&&'
exit status 1
no match for 'operator=' (operand types are 'BLEScanResults' and 'BLEScanResults*')

**Comment by EriveltonMS** [comment]
> Change your board to ESP32 Board Version 2.0.11 It does not work with 3.0.7

II made the change as indicated, but now when I compile I get the following message:
class BLEAdvertising' has no member named 'setDeviceAddress'; did you mean 'setPrivateAddress'?
Using Arduino 1.8.19 and ESP32 Dev Module

**Comment by Archit642** [comment]
Use board manager version 2.0.14
